### ISSUE TITLE
Weka Interface Implementation

### ISSUE THREAD

**Issue by daniel86** [knowrob/knowrob_addons#39]
Story: code-iai/knowrob_backlog#7

- Interface to Weka machine learning
- Feature selection: Find relevant features
- Classifcation
- Create knowrob package: Predicates that allow users to use the weka interface with episode data

**Comment by asilx** [comment]
initial commit is done! Not quite tested but will be further improved and tested with different usecases in the next sprints!

**Comment by knowrob** [comment]
Are you aware of https://github.com/knowrob/knowrob/blob/master/knowrob_common/prolog/classifiers.pl ?

**Comment by asilx** [comment]
Hi Moritz,

Yes, I am aware of classifier.pl. I have basically implemented based on this but since i need new features such as feature selection, i have created a new package for learning

**Comment by knowrob** [comment]
Cool that you've added the features, just wondering why not just extending the existing package instead of creating a new one with partially duplicated functionality?

**Comment by asilx** [comment]
knowrob_common is a package that we include almost anywhere. So, in my opinion, if we put more specific learning stuff inside,  its content will be more than "common stuff" That's why, my intention was to reachen the learning functionalities by moving stuff to a new package called knowrob_learning and to remove classifier.pl at some time point. Also, since java classes that classifier.pl depends upon is missing, i reimplemented some of things especially in java side.
